language: php

sudo: false

env:
  - WP_VERSION=latest WP_MULTISITE=0 PHP_LATEST_STABLE=7.1

matrix:
  include:
  - php: 5.3
    env: WP_VERSION=latest WP_MULTISITE=0 PHP_LATEST_STABLE=7.1
    dist: precise

before_script:
  - phpenv config-rm xdebug.ini
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - bash tests/bin/install.sh give_test root '' localhost $WP_VERSION
  - bash tests/bin/travis.sh before
  - git clone git://github.com/wimg/PHPCompatibility.git $(pear config-get php_dir)/PHP/CodeSniffer/Standards/PHPCompatibility

script:
  - phpcs --standard=PHPCompatibility --runtime-set testVersion 5.3-5.5 $(find ./tests/acceptance -name '*.php')

after_script:
  - bash tests/bin/travis.sh after